/**
 * Trading universe — generated by MISCHAR.py (G:\claude-projects\MISCHAR.py),
 * which sums real Bybit turnover24h across every product type a base asset
 * trades on (spot USDT, linear USDT, linear USDC, inverse) to find truly
 * liquid coins, then reports the actual USDT pair the bot can execute on.
 *
 * Two bugs were fixed in that script before trusting its output:
 *   1. The liquidity gate now checks the TRADEABLE USDT-pair volume, not the
 *      combined total across all product types — a coin whose volume sits
 *      mostly in USDC/inverse contracts (which this bot never touches) no
 *      longer "passes" while its actual USDT pair stays thin.
 *   2. Tokenized stocks/commodities/stablecoins (NVDA, TSLA, MSTR, XAU, XAG,
 *      PAXG, USDC, USDE, ...) are excluded — the engine's regime/ATR/leverage
 *      logic is tuned for crypto volatility, and stable pairs can't produce
 *      a real signal in the first place.
 *
 * Re-run `python MISCHAR.py` periodically (liquidity shifts) and paste the
 * refreshed TARGET_SYMBOLS array back in here.
 */
export const TARGET_SYMBOLS = [
  // ── LIQUID (>= $20M/24h, tradeable USDT pair) ─────────────────────────────
  'BTCUSDT', 'ETHUSDT', 'XRPUSDT', 'SOLUSDT', 'HYPEUSDT', 'ZECUSDT', 'DOGEUSDT',
  'TRUMPUSDT', 'ENAUSDT', '1000PEPEUSDT', 'NEARUSDT', 'SUIUSDT', 'AAVEUSDT',
  'ADAUSDT', 'PUMPFUNUSDT', 'LITUSDT', 'PENGUUSDT', 'LINKUSDT', 'TAOUSDT',
  'ONDOUSDT', 'LTCUSDT', 'VELVETUSDT', 'WLDUSDT', 'TUTUSDT', 'FARTCOINUSDT',
  'UNIUSDT', 'SNXXUSDT', 'KORUUSDT', 'BNBUSDT', 'CASHCATUSDT', 'BCHUSDT',
  'XPLUSDT', 'VIRTUALUSDT', 'SPKUSDT', 'UAIUSDT', 'GRASSUSDT', 'MONUSDT',
  'XLMUSDT', 'AVAXUSDT', 'BEATUSDT', 'INJUSDT', 'XMRUSDT',
  // ── CLOSE ($8M-$20M/24h, tradeable USDT pair) — borderline liquidity ────
  'PORTALUSDT', 'STORJUSDT', 'ASTERUSDT', 'POLUSDT', 'MNTUSDT', 'HBARUSDT',
  'MORPHOUSDT', 'WLFIUSDT', 'AEROUSDT', 'STXUSDT', 'APTUSDT', 'CRCLUSDT',
  'ARBUSDT', 'ZROUSDT', 'BTWUSDT', 'ETHFIUSDT', 'WIFUSDT', 'DASHUSDT',
  'SUPERUSDT', 'PEPEUSDT', 'SHIB1000USDT', 'ACEUSDT', 'ONGUSDT', 'DOTUSDT',
  'APEXUSDT', 'GALAUSDT', '1000BONKUSDT', 'CRVUSDT', 'VVVUSDT', 'PUMPUSDT',
  'SANDUSDT', 'ICPUSDT', 'COTIUSDT', 'LDOUSDT', 'OPUSDT', 'DRAMUSDT'
];
