export const TARGET_SYMBOLS = [
  'BTCUSDT','ETHUSDT','BNBUSDT','SOLUSDT','XRPUSDT','DOGEUSDT','TONUSDT','ADAUSDT','AVAXUSDT','TRXUSDT',
  'DOTUSDT','BCHUSDT','NEARUSDT','MATICUSDT','ICPUSDT','UNIUSDT','LTCUSDT','ETCUSDT','APTUSDT','SHIBUSDT',
  'LINKUSDT','XLMUSDT','ATOMUSDT','FILUSDT','HBARUSDT','ARBUSDT','OPUSDT','IMXUSDT','MKRUSDT','INJUSDT',
  'GRTUSDT','SUIUSDT','SEIUSDT','TIAUSDT','RNDRUSDT','FETUSDT','THETAUSDT','FTMUSDT','AAVEUSDT','ALGOUSDT',
  'FLOWUSDT','AXSUSDT','SANDUSDT','MANAUSDT','SNXUSDT','LDOUSDT','EGLDUSDT','XTZUSDT','EOSUSDT','NEOUSDT',
  'GALAUSDT','CHZUSDT','APEUSDT','CRVUSDT','LRCUSDT','ENAUSDT','WLDUSDT','STXUSDT','MINAUSDT','CFXUSDT',
  'RUNEUSDT','COMPUSDT','DYDXUSDT','GMXUSDT','KAVAUSDT','ZILUSDT','IOTAUSDT','CAKEUSDT','1INCHUSDT','MASKUSDT',
  'PENDLEUSDT','ARUSDT','BLURUSDT','WOOUSDT','SKLUSDT','CELOUSDT','KSMUSDT','ZRXUSDT','YFIUSDT','BATUSDT',
  'ENSUSDT','SSVUSDT','ANKRUSDT','BANDUSDT','OGNUSDT','ONTUSDT','WAVESUSDT','STORJUSDT','ONEUSDT','HOTUSDT',
  'IOSTUSDT','VETUSDT','DASHUSDT','ZENUSDT','QTUMUSDT','ZECUSDT','ICXUSDT','RVNUSDT','GLMRUSDT','BNTUSDT'
];
