/**
 * Trading universe — generated by MISCHAR.py (G:\claude-projects\MISCHAR.py),
 * which sums real Bybit turnover24h across every product type a base asset
 * trades on (spot USDT, linear USDT, linear USDC, inverse) to find truly
 * liquid coins, then reports the actual tradeable Spot USDT pair.
 *
 * Bugs fixed in that script before trusting its output (2026-08-26):
 *   1. trade_symbol now prefers spot USDT over linear USDT. The bot's price
 *      pipeline (fetchBybitAllTickers / getAggregatedPrices) only ever reads
 *      Bybit's SPOT tickers — a symbol chosen from linear-only naming (e.g.
 *      "1000PEPEUSDT", which doesn't exist on Spot at all; Spot lists the
 *      same coin as "PEPEUSDT") could never get live data, so it just sat as
 *      a dead, permanently-pending slot in the universe.
 *   2. Multiplier-prefixed linear symbols (1000PEPE, 1000BONK, SHIB1000) are
 *      normalized to their real base (PEPE, BONK, SHIB) before grouping, so
 *      the same coin can no longer enter TARGET_SYMBOLS twice under two
 *      different symbol strings.
 *   3. A coin with no real Spot USDT pair (liquid only via linear/USDC/
 *      inverse) is excluded outright — same unreachable-symbol reason as #1
 *      — instead of being included with a symbol nothing can ever fetch.
 *   4. Tokenized stocks/commodities/stablecoins (NVDA, TSLA, MSTR, XAU, XAG,
 *      PAXG, USDC, USDE, ...) are excluded — the engine's regime/ATR/leverage
 *      logic is tuned for crypto volatility, and stable pairs can't produce
 *      a real signal in the first place.
 *
 * Re-run `python MISCHAR.py` periodically (liquidity shifts) and paste the
 * refreshed TARGET_SYMBOLS array back in here.
 */
export const TARGET_SYMBOLS = [
  // ── LIQUID (>= $20M/24h across all venues, real Spot USDT pair) ──────────
  'BTCUSDT', 'ETHUSDT', 'SOLUSDT', 'XRPUSDT', 'HYPEUSDT', 'DOGEUSDT', 'ENAUSDT',
  'TRUMPUSDT', 'SUIUSDT', 'ZROUSDT', 'ADAUSDT', 'PEPEUSDT', 'NEARUSDT',
  'LINKUSDT', 'AAVEUSDT', 'LITUSDT', 'STXUSDT', 'ONDOUSDT', 'PENGUUSDT',
  'WLDUSDT', 'LTCUSDT', 'UNIUSDT', 'XLMUSDT', 'BNBUSDT', 'MONUSDT', 'AGIUSDT',
  'INJUSDT', 'XPLUSDT', 'AVAXUSDT', 'POLUSDT', 'BMTUSDT', 'APTUSDT', 'SPXUSDT',
  'ASTERUSDT', 'WIFUSDT', 'GRAMUSDT',
  // ── CLOSE ($8M-$20M/24h across all venues, real Spot USDT pair) ──────────
  'VVVUSDT', 'VIRTUALUSDT', 'TACUSDT', 'MNTUSDT', 'JASMYUSDT', 'TRXUSDT',
  'PORTALUSDT', 'PUMPUSDT', 'HBARUSDT', 'BCHUSDT', 'DOTUSDT', 'POPCATUSDT',
  'WLFIUSDT', 'ETHFIUSDT', 'HUSDT', 'ARBUSDT', 'CRVUSDT', 'AEROUSDT',
  'HOLOUSDT', 'KIIUSDT', 'BONKUSDT', 'OPUSDT', 'FFUSDT', 'CCUSDT', 'JUPUSDT'
];
